#!/usr/bin/ruby

lib = File.expand_path('../lib', __FILE__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)

require 'rubygems'
require 'bundler/setup'

require 'securerandom'
require 'benchmark'
require 'scraper'

dir    = File.join(__dir__, "vendor/mount/#{SecureRandom.uuid}")
stocks = IO.read('vendor/mount/f03dc1bf-cacb-467b-8ff8-24c3e0716e70.txt').split
count  = 0

puts "Scraping #{stocks.count} stocks from consorsbank..."

time = Benchmark.realtime do
  count = Scraper.new(drop_box: dir).run(*stocks)
end

puts "Scraped #{count} stocks"
puts "Time elapsed #{time.round(2)} seconds"
